src/game.htm

This resolves https://github.com/packardbell95/tardquest/issues/1
When reaching the end of the dungeon, the game continues by descending a floor and generating a new map
Descending also has a 50% chance of displaying random flavor text to set the mood of the player's perilous journey

Reaching the exit now descends deeper into the dungeon

---

src/game.htm

This PR introduces the following enemies and should resolve https://github.com/packardbell95/tardquest/issues/3 for the time being:
```
___.---+.
.--''       | '.
|           |  |
|     ______|  |
|----'      |  |
|       [==]|  |
|           |  |
|           |  |
|___        |  |
'---.___|.-'
```
```
.--.
|oO|
..-\TT/-..
'          '
( )      ( )
( |------| )
'W . || . W'
(__)(__)
```
```
.        .--.
|\      .-:;
: \    < O |'
\ \   ;    '.
\/\-(    (. '
(_)/ -_    ' ;
'-; ;
/|\/|\
```
```
*
/ \
.-./___\.-.
\/ o o \/
(__(_)__)
/ : \
(_|-|_)
(__|__)
```
Enemies also now have IDs to reference instead of their display names which should make it easier to change the display names if we ever decide on adjusting casing or anything like that

Adding even more enemies

---

src/game.htm

The stat's intended functionality SHOULD be working properly now. I haven't done extensive testing and it may or may not be unbalanced, but just going off by changing the base player PRS stat, it definitely seems to be working correctly now.
I also changed some of the flavor text while I was at it. We can adjust values later after we start adding level scaling for the enemies.
This will close #17

PRS stat fixed

---

src/game.htm

This also includes the code I used to fix the PRS stat, hence why I branched this off of that pull request. Please do lmk if I messed something up doing so.
You can now speak outside of combat by pressing T (originally was going to be ENTER but that was causing some major problems), and if you have any party members, a random member will respond with a random line of dialogue. More preset lines of dialogue are very much welcome.
This will close #5

Add ability to speak outside of combat

---

src/game.htm

Enemies now hit harder, get larger HP pools, and give more EXP + BTC as you delve deeper into the depths of the Tardspire (yes that's what I'm calling it now). In addition to this, I added a bunch of colorization to make the battle log more readable, and fixed the missing DEF stat functionality. Now you should be taking less damage as you level the stat up, as intended. I made double sure the new armor honors the defense increases, though I'm not 100% confident that EVERYTHING is working as intended. It seems to be though. Feel free to test different level scaling values and such, I didn't spend too much time finding a good balance.
`            const floorBoost = Math.floor(floor / 2); // Scale every 2 floors
if (floorBoost > 0) {
currentEnemy.hp += floorBoost * 5; // +5 HP per scaling …

Level scaling + various others

---

src/game.htm

The merchant would take your money, but items would not show up in the player's inventory
This is because the items were being put into `player.inventory` which is the entire inventory plus functional data rather than `player.inventory.contents` which is where the item list actually lives
This PR solves the problem by referencing the correct location for inventory storage after purchase
1. Check your inventory and note its contents
2. Visit the merchant
3. Buy items from him
4. Leave
5. Open your inventory again
6. Observe that the content count matches what was seen previously, plus whatever what purchased from the merchant
Resolves https://github.com/packardbell95/tardquest/issues/25

Fixing merchant purchases

---

src/game.htm

The party list now has it's own container below the viewport, and the control hints now also have their own container under the map key. Player stats display above the first person view and enemy art.

UI Adjustments

---

src/game.htm

General list of fixes and changes:
- Music toggle button works as intended; which in turn, caused a crap ton of other bugs, which were also fixed. Basically had to do some code restructuring.
- Bottom-left control hints box no longer disappears when entering any menus (inventory, merchant, gambler)
- Your HP now updates immediately when consuming a healing item
- Changed some persuasion stat scaling values. I felt like it was too easy to persuade too many enemies earlygame. I would appreciate some feedback on this one
- The reset button was reworked so that instead of simply linking to the game page itself, it runs a script to reload the game. This alleviates just a little bit of the hassle for anyone who wants to fork this game, port it to Electron, etc.
This will close #30

Music toggle fix + various

---

src/game.htm

This PR adds the ability to buy weapons and armor from the merchant
To make this easier to implement, a new menu system has been introduced that consolidates the menus for the merchant and gambler interactions as well as the inventory system
Equipment is always only upgradable. This means that any gear that is bought will automatically make any equal or inferior gear inaccessible to the player
| <img width="300" src="https://github.com/user-attachments/assets/3cfc71a1-4b54-409d-89b2-834a477ca600"> |
| --- |
| Upgrading weapons and armor prevents all inferior equipment from being purchased |
The new menus offer a simple and consistent interface for interaction
| Key | Action |
| --- | --- |
| ↑/W | Move the cursor up |
| ↓/S | Move the cursor down |
| Escape | Back out of the current menu …

Buying Equipment, Menu Updates

---

src/game.htm

Treasure chests (marked as "T" tiles) now spawn on each floor in a random quantity of 1-5. Landing on a T tile will display a menu utilizing our new menu system, allowing the player to choose whether to open the chest or not. Leaving the chest behind will allow the player to come back to it later if they're feeling paranoid... because each chest placed during map generation ALSO now has a 20% chance of being a Mimic Chest! Obviously, if a chest is marked as a mimic, opening said chest will throw you into battle with one. You do not want to mess with these guys  early on, but if you do manage to defeat one, you will be given a decently sizeable chunk of change. However, you will be granted no EXP.
And since I felt like the system was extremely outdated, I reworked the healing tile system. …

Chests, chest mimics, and healing tile rework

---

src/game.htm

You can now scroll through pages in menus if a list exceeds 8 items. All menus have this functionality by default. This will be very important for when we start to add more items and equipment, and potentially even the Pokedex/bestiary that was mentioned previously.
https://github.com/user-attachments/assets/79bd66e5-4a4c-461f-8f8f-15411e37ab88

Added menu scrolling

---

src/game.htm

I've added a Luck (LUK) stat that increases your critical hit rate, as well as slightly increasing the amount of BTC you can find in chests. This also means the player can now randomly land critical hits on enemies.
Much like the starting character building screen, you can now allocate 3 points towards your stats when you level up.
I've also made various other under-the-hood changes. The biggest one here is the SPD-based movement delay no longer affects other inputs, so you can now confirm menu selections, rotate the character, etc before the movement delay timer is over. Much less clunky, needless to say.

Luck stat added, level up point allocation added

---

src/game.htm

The player is now able to manually equip obtained weapons and armor, meaning submenus were also added to the inventory screen. Now when you open the inventory, you can select the "Equipment" or "Items" menu. I've pretty much removed the "notAnUpgrade" logic from equipment purchases so you can actually own all the pieces you buy, rather than it working like a linear upgrade system. I kept the .muted id though in case we do still want to use it for something in the future. One minor but annoying issue I ran into was that when you first buy something from the merchant, you lose the armor/item you start the game off with. Could not figure out how to fix that, so my sorry workaround was the create new starting equipment that is weaker, but can still be bought for free if you really wanted to …

Added inventory submenus

---

src/game.htm

Increasing LUK now somewhat increases your chances at landing a 12 in the gambler diceroll minigame by 3% per point. I also noticed in the recent past that landing a 12 (which was also COMICALLY rare btw) would not trigger a win state. Something must have broke in an update sometime down the line, but that's been fixed here. Also nerfed the crit chance rate when leveling LUK from 2% down to 1%.

Changes to LUK effects + Gambler fix

---

src/game.htm

After setting a fixed font in https://github.com/packardbell95/tardquest/pull/53, the side walls were truncated. This PR extends the display to occupy 6 more characters in height and adjusts the side wall art to match. So now the walls no longer appear truncated
| <img width="300" src="https://github.com/user-attachments/assets/95af380c-d78b-47e2-bf2e-f265e72bd20d"> | <img width="300" src="https://github.com/user-attachments/assets/b0de7f80-f7d8-47cc-81c1-13d8dc9b28cc"> |
| --- | --- |
| **Before:** Side walls appear truncated | **After:** Walls are no longer cut off |
Fixes https://github.com/packardbell95/tardquest/issues/54

Extending display height to allow side walls to be taller

---

src/game.htm

You can now have a maximum of 3 members in your party, and by default, can only make two attempts at persuasion per battle. I've added a ring (Ring of Amplified Audio) that increases the attempt limit to 3. This won't spawn in chests and can only be purchased from the Merchant.
I've also adjusted the PRS stat scaling so that it caps out at 100. Meaning, for example, if you had 12 PRS, your chances at persuading an enemy would be 12%, and so on. I've increased the base PRS stat to 15 to reflect this change.
I've also fixed a couple of those bugs that were brought up. Player input is now locked while gambling and the "You died on floor X" message has been moved to the battle log.
This will close #56 , #55 , and #51 .

Party size + attempt limit, new ring, PRS stat scaling changes

---

src/game.htm

STR - Each point increases ATK by 1
END - Increases your max carry load
LOAD - Your carry load, duh
Carrying too many items will debuff your SPD. Debuffing starts with 5% when you've reached 50% of your maximum LOAD, and gradually gets worse as you pick up more items, capping out at a 100% debuff. In the future I may very likely make it so weapons and armor take up your LOAD as well, in which case I would need to add a sell menu for the Merchant.
To make the new stats (especially END) less redundant, I've also made it so weapons require a certain amount of STR to equip, same deal with armor and END.
The amount of points given to you during initialization and level ups have been increased. When leveling up, you can now only allocate 2 points per stat at a time. This ensures you're at least …

STR+END stats and carry weight system added

---

src/game.htm

After leveling up, the player would lose all rolled over experience. For example, if the player had 19/20 EXP and killed an enemy that gave them 5 EXP, they would level up and be set at 0 EXP instead of 4. The changes in this PR carry over the experience into the next level
| <img src="https://github.com/user-attachments/assets/25bc2dc2-f5c2-4fc5-9640-aa871c0f9eec" width="300"> |
| --- |
| Starting with 39/40 EXP and leveling up after earning 6 EXP leaves the player with 5 EXP instead of 0 |
Leveling up now happens by calling `player.levelUp()` rather than taking place in the menu
We also had some old level up code still around that wasn't being used by anything, so I removed that as well
Finally, I renamed the level up option from `_confirm` to `confirm` since the underscore prefix is …

Adding EXP rollover, removing old unused level up code

---

src/game.htm

The Merchant now has a menu that allows you to sell consumable items, weapons, armor, and rings. This was necessary to allow me to add weight to weapons/armor/rings, which has also been done here. Also nerfed the Pectoral Piercing. Way too OP for how little BTC it costs.
The Merchant also gives you different responses depending on what item type you attempt to sell that you aren't able to sell if it's already equipped.

Merchant sell menu + weight for armor and weapons

---

src/game.htm

This includes the new dialogue system we discussed where when using the TALK function while you have party members, instead of pulling a random preset static message, it will instead pull random words from word/phrase pools and insert them into wordslots to create a sentence. Now you will have brilliantly nonsensical and braindead randomized dialogue such as the following:
Under the enemies object, you can easily define a specific set of word/phrase pools for specific enemies. Any that don't have their own unique set will use the default fallback set instead. I adjusted the battlelog text gradient as well (which is _not_ demonstrated in the first screenshot).
I've once again changed how the textbox is presented as well.
I've also added a toggle for level up animations via the settings …

New dialogue system + localstorage settings

---

src/game.html

Whenever you enter a menu or NPC interaction, the minimap area is replaced by an animated ASCII portrait. Currently this covers the settings, menu, merchant, and gambler menus. More can be added later for the submenus.
Example video:
https://github.com/user-attachments/assets/0f65b916-cf11-4282-89c8-1654b9fa4973
I also debuffed the LOAD gain when levelling END because you really just don't get heavy often enough

Animated menu + NPC portraits

---

README.md
src/game.html
src/scripts/sam.js

This PR changes the following:
- Adding speech synthesis for party members and NPCs
- Adding the ability to toggle speech synthesis in the Game Settings menu
- Party member names now appear `<like this>` rather than `like this:`
- Minimizing the number of places to update styles of player speech in `player.say()`
- Changing an error message from `console.log()` to `console.error()`
- Removing unneeded whitespace
- Removing unused `returnToTitleScreen` case in the Game Settings menu
https://github.com/user-attachments/assets/a4558bbb-3ddc-4579-b341-fc8df318ab9a
The speech synthesis in this update is made possible by [Imrane03/better-sam (SAM Software Automatic Mouth)](https://github.com/Imrane03/better-sam?tab=readme-ov-file#sam-software-automatic-mouth)
Some modifications to SAM have been …

Adding speech synthesis for party members and NPCs, misc other updates

---

src/game.html

Gambling chances used to scale in a strange way, resulting in the LUK stat softcapping at a rather low value, allowing you to easily win the diceroll relatively early on.
This now behaves like the PRS stat where the chances are on a 0-100% scale in accordance to your stat number. For example, if your LUK stat is at 20, your chances at winning the diceroll minigame are 20%. The BTC gain from chests has been left untouched here.
To reflect this change, the base starting LUK stat has been increased to 17. So you begin with a meager 17% chance at winning the minigame, and chest rewards aren't too high from the start.

LUK scaling changes

---

src/game.html
src/scripts/Map.js
src/scripts/Menu.js
src/scripts/Tooltip.js

This PR aims to provide select performance improvements for the game through restructuring the map, minimap, battle log, and menu
This PR adjusts the map's functionality to wrap it into its own `Map` class which handles a lot of placement and rendering functionality with more ease
Previously, map cells were tracked in the global `MAP` array. `MAP` has now been converted to an instance of the `Map` class. This means that `MAP` still holds the contents of the game's map, but now has helper methods associated with it that can be used to perform operations on the map
In particular, we previously were setting map cells by creating new `MapCell()` objects in the array's coordinates:
```javascript
MAP[y][x] = new MapCell(...);
```
Now, we can set these with `Map.setCell()`:
```javascript …
```

Optimize Minimap Rendering Function

---

src/game.html

A fairly simple set of small changes. The Ring of Sightliness will no longer allow you to see directly through walls, and basically just increases the player's FOV cone. Below is an annotated (maybe somewhat kinda inaccurate) screenshot of what the player's FOV cone looks like after equipping the ring, and what tiles are being revealed.
The equipment menu is also now inaccessible during combat, which was a decision made to reflect the upcoming clickable UI we have planned, complete with a bit of flavor text in the battle log.
This PR will close #65

Ring of Sightliness Changes + Equipment menu combat limit

---

src/game.html

When holding a torch, the glow encroaches on the Viewport header. This PR stops that from happening
Closes https://github.com/packardbell95/tardquest/issues/123
| <img src="https://github.com/user-attachments/assets/a9a40d37-5c13-4f34-9d91-38c24d9f0d0a" width="300"> | <img src="https://github.com/user-attachments/assets/fd29d544-4978-474a-8e1c-95a206d32bf2" width="300"> |
| --- | --- |
| **Before:** Torch glow encroaching on the Viewport header | **After:** The glow is contained |

Preventing Viewport Overflow

---

src/game.html

When using items in the sidebar, an item's button in the sidebar will be removed when the player no longer has any more. However, any tooltip reference that still exists will not be freed, so the tooltip on the page will persist since nothing exists to dismiss it
This PR fixes the problem by deleting the tooltip reference if the last of an item was used
| <img src="https://github.com/user-attachments/assets/4ce69977-1471-431b-b342-0b041d37c0ed" width="300"> |
| --- |
| Tooltips now being cleared after using up items |
Closes https://github.com/packardbell95/tardquest/issues/142

Deleting tooltips when the sidebar button exhausts an item

---

src/game.html

The current pigeon moves by replacing map cells. This causes any cells that the pigeon flies over to be cleared since each is replaced by a floor cell
This PR fixes the issue by adding the pigeon as one of the `GameMap`'s `entities` instead of having it manage its own tile space on the map directly. Changes here also remove references to the notion that the pigeon is a unique entity since there are many of them
Closes https://github.com/packardbell95/tardquest/issues/146
| <img src="https://github.com/user-attachments/assets/57db6f2c-826d-4e14-962d-ee79f8b27aa7"> |
| --- |
| The pigeon moving through the map without overwriting cells, except for when it dies |
I tested this by doing the following:
1. Run `localStorage.setItem("pigeonPendingMessage", "ayy lmao")`
2. Reload the page
3. …

Moving the carrier pigeon to an entity instead of a grid cell

---

src/game.html
src/scripts/gamepad.js
src/scripts/tardboard.js

This PR brings `tardboard.js` off external hosting and into the main `scripts` directory along with a complete overhaul of the dialog box UI and gamepad support for submitting scores. Keyboard can still be used as normal.
Right now, the dialog box is still injected by the script, we can either address this later or leave it as is.
Closes #124 
> Me struggling to use my flight stick to submit a score
> [!NOTE]
> The captcha status has been moved to the console log. The Submit button will be disabled after pressing it in cases where verification is still pending.

Improve TardBoard UI + TardBoard Gamepad Support
